spring.application.name=escola

# Configuracoes do banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/senailogin?useSSL=false&serverTimezone=UTC

#o nome do banco de dados voce que escolhe pra rodar na sua maquina local


#usesname e password vai ser do seu MySQL Workbench
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true